/// Major cities that are not IANA zone names, mapped to their time zone so
/// they show up in world-clock search (San Antonio, Dallas, Mumbai, …).
const Map<String, String> kCityAliases = {
  // US — Central
  'San Antonio': 'America/Chicago',
  'Dallas': 'America/Chicago',
  'Houston': 'America/Chicago',
  'Austin': 'America/Chicago',
  'Fort Worth': 'America/Chicago',
  'Oklahoma City': 'America/Chicago',
  'Kansas City': 'America/Chicago',
  'St Louis': 'America/Chicago',
  'Minneapolis': 'America/Chicago',
  'Milwaukee': 'America/Chicago',
  'New Orleans': 'America/Chicago',
  'Memphis': 'America/Chicago',
  'Nashville': 'America/Chicago',
  'Birmingham': 'America/Chicago',
  'Omaha': 'America/Chicago',
  'Tulsa': 'America/Chicago',
  'Wichita': 'America/Chicago',
  'Des Moines': 'America/Chicago',
  // US — Eastern
  'Boston': 'America/New_York',
  'Philadelphia': 'America/New_York',
  'Washington DC': 'America/New_York',
  'Atlanta': 'America/New_York',
  'Miami': 'America/New_York',
  'Orlando': 'America/New_York',
  'Tampa': 'America/New_York',
  'Charlotte': 'America/New_York',
  'Raleigh': 'America/New_York',
  'Pittsburgh': 'America/New_York',
  'Cleveland': 'America/New_York',
  'Columbus': 'America/New_York',
  'Cincinnati': 'America/New_York',
  'Baltimore': 'America/New_York',
  'Richmond': 'America/New_York',
  'Jacksonville': 'America/New_York',
  'Buffalo': 'America/New_York',
  // US — Mountain
  'Salt Lake City': 'America/Denver',
  'Albuquerque': 'America/Denver',
  'Colorado Springs': 'America/Denver',
  'El Paso': 'America/Denver',
  'Tucson': 'America/Phoenix',
  'Mesa': 'America/Phoenix',
  // US — Pacific
  'San Francisco': 'America/Los_Angeles',
  'San Diego': 'America/Los_Angeles',
  'San Jose': 'America/Los_Angeles',
  'Seattle': 'America/Los_Angeles',
  'Portland': 'America/Los_Angeles',
  'Las Vegas': 'America/Los_Angeles',
  'Sacramento': 'America/Los_Angeles',
  'Oakland': 'America/Los_Angeles',
  'Fresno': 'America/Los_Angeles',
  'Spokane': 'America/Los_Angeles',
  // Canada
  'Montreal': 'America/Toronto',
  'Ottawa': 'America/Toronto',
  'Quebec City': 'America/Toronto',
  'Calgary': 'America/Edmonton',
  // Latin America
  'Rio de Janeiro': 'America/Sao_Paulo',
  'Brasilia': 'America/Sao_Paulo',
  'Guadalajara': 'America/Mexico_City',
  'Monterrey': 'America/Monterrey',
  'Medellin': 'America/Bogota',
  'Quito': 'America/Guayaquil',
  // Europe
  'Munich': 'Europe/Berlin',
  'Frankfurt': 'Europe/Berlin',
  'Hamburg': 'Europe/Berlin',
  'Cologne': 'Europe/Berlin',
  'Barcelona': 'Europe/Madrid',
  'Valencia': 'Europe/Madrid',
  'Seville': 'Europe/Madrid',
  'Milan': 'Europe/Rome',
  'Naples': 'Europe/Rome',
  'Turin': 'Europe/Rome',
  'Venice': 'Europe/Rome',
  'Florence': 'Europe/Rome',
  'Lyon': 'Europe/Paris',
  'Marseille': 'Europe/Paris',
  'Nice': 'Europe/Paris',
  'Manchester': 'Europe/London',
  'Birmingham UK': 'Europe/London',
  'Edinburgh': 'Europe/London',
  'Glasgow': 'Europe/London',
  'Liverpool': 'Europe/London',
  'Leeds': 'Europe/London',
  'Rotterdam': 'Europe/Amsterdam',
  'The Hague': 'Europe/Amsterdam',
  'Antwerp': 'Europe/Brussels',
  'Geneva': 'Europe/Zurich',
  'Basel': 'Europe/Zurich',
  'Krakow': 'Europe/Warsaw',
  'Gdansk': 'Europe/Warsaw',
  'St Petersburg': 'Europe/Moscow',
  // Middle East / Africa
  'Tel Aviv': 'Asia/Jerusalem',
  'Abu Dhabi': 'Asia/Dubai',
  'Doha': 'Asia/Qatar',
  'Mecca': 'Asia/Riyadh',
  'Jeddah': 'Asia/Riyadh',
  'Cape Town': 'Africa/Johannesburg',
  'Durban': 'Africa/Johannesburg',
  'Alexandria': 'Africa/Cairo',
  'Casablanca City': 'Africa/Casablanca',
  // Asia
  'Mumbai': 'Asia/Kolkata',
  'Delhi': 'Asia/Kolkata',
  'New Delhi': 'Asia/Kolkata',
  'Bangalore': 'Asia/Kolkata',
  'Chennai': 'Asia/Kolkata',
  'Hyderabad': 'Asia/Kolkata',
  'Pune': 'Asia/Kolkata',
  'Beijing': 'Asia/Shanghai',
  'Shenzhen': 'Asia/Shanghai',
  'Guangzhou': 'Asia/Shanghai',
  'Chengdu': 'Asia/Shanghai',
  'Osaka': 'Asia/Tokyo',
  'Kyoto': 'Asia/Tokyo',
  'Nagoya': 'Asia/Tokyo',
  'Sapporo': 'Asia/Tokyo',
  'Busan': 'Asia/Seoul',
  'Incheon': 'Asia/Seoul',
  'Hanoi': 'Asia/Ho_Chi_Minh',
  'Da Nang': 'Asia/Ho_Chi_Minh',
  'Phuket': 'Asia/Bangkok',
  'Chiang Mai': 'Asia/Bangkok',
  'Bali': 'Asia/Makassar',
  'Surabaya': 'Asia/Jakarta',
  'Cebu': 'Asia/Manila',
  // Oceania
  'Canberra': 'Australia/Sydney',
  'Gold Coast': 'Australia/Brisbane',
  'Wellington': 'Pacific/Auckland',
  'Christchurch': 'Pacific/Auckland',
};
